initial notebook -- organization and data prep

mostly for messing around and testing

In [1]:
import pandas as pd
import numpy as np
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import torch
import tensorflow

pd.set_option('display.max_columns', None)

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
df = pd.read_csv("../data/matchups-2007.csv")
print(df.head())  # View first few rows
print(df.info())  # Check data types & missing values

           game  season home_team away_team  starting_min  end_min  \
0  200610310LAL    2007       LAL       PHO             0        5
1  200610310LAL    2007       LAL       PHO             6        7
2  200610310LAL    2007       LAL       PHO             8        9
3  200610310LAL    2007       LAL       PHO            10       10
4  200610310LAL    2007       LAL       PHO            11       11

         home_0         home_1         home_2         home_3  ... pf_visitor  \
0  Andrew Bynum     Lamar Odom    Luke Walton  Sasha Vujacic  ...          0
1  Andrew Bynum     Lamar Odom    Luke Walton  Sasha Vujacic  ...          0
2    Lamar Odom    Luke Walton  Maurice Evans   Ronny Turiaf  ...          0
3    Lamar Odom    Luke Walton  Maurice Evans   Ronny Turiaf  ...          0
4   Luke Walton  Maurice Evans   Ronny Turiaf   Smush Parker  ...          1

  reb_visitor dreb_visitor oreb_visitor to_visitor pts_visitor  pct_visitor  \
0           7            7            0          1          22     0.909091
1           1            1            0          0           9     0.666667
2           1            1            0          1           2     0.500000
3           1            0            1          1           3     0.500000
4           1            1            0          1           2     1.000000

   pct_2_visitor  pct_3_visitor  outcome
0           1.00       0.666667       -1
1           0.75       0.500000       -1
2           0.50       0.000000        1
3           0.00       0.500000        1
4           1.00       0.000000       -1

[5 rows x 53 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27500 entries, 0 to 27499
Data columns (total 53 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   game           27500 non-null  object
 1   season         27500 non-null  int64
 2   home_team      27500 non-null  object
 3   away_team      27500 non-null  object
 4   starting_min   27500 non-null  int64
 5   end_min        27500 non-null  int64
 6   home_0         27500 non-null  object
 7   home_1         27500 non-null  object
 8   home_2         27500 non-null  object
 9   home_3         27500 non-null  object
 10  home_4         27500 non-null  object
 11  away_0         27500 non-null  object
 12  away_1         27500 non-null  object
 13  away_2         27500 non-null  object
 14  away_3         27500 non-null  object
 15  away_4         27500 non-null  object
 16  fga_home       27500 non-null  int64
 17  fta_home       27500 non-null  int64
 18  fgm_home       27500 non-null  int64
 19  fga_2_home     27500 non-null  int64
 20  fgm_2_home     27500 non-null  int64
 21  fga_3_home     27500 non-null  int64
 22  fgm_3_home     27500 non-null  int64
 23  ast_home       27500 non-null  int64
 24  blk_home       27500 non-null  int64
 25  pf_home        27500 non-null  int64
 26  reb_home       27500 non-null  int64
 27  dreb_home      27500 non-null  int64
 28  oreb_home      27500 non-null  int64
 29  to_home        27500 non-null  int64
 30  pts_home       27500 non-null  int64
 31  pct_home       27500 non-null  float64
 32  pct_2_home     27500 non-null  float64
 33  pct_3_home     27500 non-null  float64
 34  fga_visitor    27500 non-null  int64
 35  fta_visitor    27500 non-null  int64
 36  fgm_visitor    27500 non-null  int64
 37  fga_2_visitor  27500 non-null  int64
 38  fgm_2_visitor  27500 non-null  int64
 39  fga_3_visitor  27500 non-null  int64
 40  fgm_3_visitor  27500 non-null  int64
 41  ast_visitor    27500 non-null  int64
 42  blk_visitor    27500 non-null  int64
 43  pf_visitor     27500 non-null  int64
 44  reb_visitor    27500 non-null  int64
 45  dreb_visitor   27500 non-null  int64
 46  oreb_visitor   27500 non-null  int64
 47  to_visitor     27500 non-null  int64
 48  pts_visitor    27500 non-null  int64
 49  pct_visitor    27500 non-null  float64
 50  pct_2_visitor  27500 non-null  float64
 51  pct_3_visitor  27500 non-null  float64
 52  outcome        27500 non-null  int64
dtypes: float64(6), int64(34), object(13)
memory usage: 11.1+ MB
None

In [ ]:
df.head()

,game,season,home_team,away_team,starting_min,end_min,home_0,home_1,home_2,home_3,home_4,away_0,away_1,away_2,away_3,away_4,fga_home,fta_home,fgm_home,fga_2_home,fgm_2_home,fga_3_home,fgm_3_home,ast_home,blk_home,pf_home,reb_home,dreb_home,oreb_home,to_home,pts_home,pct_home,pct_2_home,pct_3_home,fga_visitor,fta_visitor,fgm_visitor,fga_2_visitor,fgm_2_visitor,fga_3_visitor,fgm_3_visitor,ast_visitor,blk_visitor,pf_visitor,reb_visitor,dreb_visitor,oreb_visitor,to_visitor,pts_visitor,pct_visitor,pct_2_visitor,pct_3_visitor,outcome
0,200610310LAL,2007,LAL,PHO,0,5,Andrew Bynum,Lamar Odom,Luke Walton,Sasha Vujacic,Smush Parker,Boris Diaw,Kurt Thomas,Raja Bell,Shawn Marion,Steve Nash,10,4,4,7,3,3,1,3,0,1,1,1,0,1,9,0.400000,0.428571,0.333333,11,1,10,8,8,3,2,6,0,0,7,7,0,1,22,0.909091,1.00,0.666667,-1
1,200610310LAL,2007,LAL,PHO,6,7,Andrew Bynum,Lamar Odom,Luke Walton,Sasha Vujacic,Smush Parker,Amar'e Stoudemire,Leandro Barbosa,Raja Bell,Shawn Marion,Steve Nash,3,0,2,2,2,1,0,1,0,0,2,2,0,2,4,0.666667,1.000000,0.000000,6,0,4,4,3,2,1,4,0,0,1,1,0,0,9,0.666667,0.75,0.500000,-1
2,200610310LAL,2007,LAL,PHO,8,9,Lamar Odom,Luke Walton,Maurice Evans,Ronny Turiaf,Smush Parker,Amar'e Stoudemire,Leandro Barbosa,Raja Bell,Shawn Marion,Steve Nash,4,0,2,4,2,0,0,2,1,1,2,1,1,2,4,0.500000,0.500000,0.000000,2,2,1,2,1,0,0,1,0,0,1,1,0,1,2,0.500000,0.50,0.000000,1
3,200610310LAL,2007,LAL,PHO,10,10,Lamar Odom,Luke Walton,Maurice Evans,Ronny Turiaf,Smush Parker,Boris Diaw,James Jones,Kurt Thomas,Leandro Barbosa,Marcus Banks,2,0,2,2,2,0,0,1,0,0,0,0,0,0,4,1.000000,1.000000,0.000000,2,0,1,0,0,2,1,1,0,0,1,0,1,1,3,0.500000,0.00,0.500000,1
4,200610310LAL,2007,LAL,PHO,11,11,Luke Walton,Maurice Evans,Ronny Turiaf,Smush Parker,Vladimir Radmanovic,Boris Diaw,James Jones,Kurt Thomas,Leandro Barbosa,Marcus Banks,2,0,1,2,1,0,0,1,0,1,0,0,0,0,2,0.500000,0.500000,0.000000,1,0,1,1,1,0,0,1,0,1,1,1,0,1,2,1.000000,1.00,0.000000,-1